### ISSUE TITLE
Add Code Quality Badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/general-feedback#26]
**Describe the bug**
Add code quality badge to the repo

**Additional context**
Add Code Quality badge below name of the app in README file

just copy the below code and add it in readme below downloads code 

`[![Codacy Badge](https://api.codacy.com/project/badge/Grade/d36e50dd143d4616842556a8ec386090)](https://www.codacy.com/app/arshadkazmi42/general-feedback?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=arshadkazmi42/general-feedback&amp;utm_campaign=Badge_Grade)`

**To work on this**
1. Put a comment here who ever is working on it.
2. Also tag this issue in your Pull Request description.

_**Note:** Anyone who is not following above two steps, their PR will be rejected

**Comment by dhoeric** [comment]
I can work on this issue!

**Comment by arshadkazmi42** [comment]
@dhoeric You have already done one similar fix in one of the other repo, So I will keep this issue for others, closing your PR.

**Comment by joshghent** [comment]
Hey can I work on this one @arshadkazmi42 please?

**Comment by nikmanG** [comment]
Guess I'll do it then for the once-off.

**Comment by helloart3mis** [comment]
I can work on this :)

**Comment by arshadkazmi42** [comment]
@joshghent You just have to comment that you are working on it and create a PR. You can checkout some of our other issues
@helloart3mis Thank you for working on this.
