### ISSUE TITLE
Add yourself to Contributors.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/general-feedback#6]
If you are starting with opensource contributions, this is best to start with.
just go ahead and add your details to Contributors.md file in the same format as other's details.

**Comment by andeladenaro** [comment]
Ok sure, be there..

**Comment by andeladenaro** [comment]
I've add my self to contributor.md, thanks.

**Comment by arshadkazmi42** [comment]
Awsome @andeladenaro

**Comment by sankalpchauhan-me** [comment]
Updated contributors[dot]md and added compressed gif of the app to show it's working in readme[dot]md
PR #22

**Comment by sankalpchauhan-me** [comment]
Updated Contributors.md PR #25
