### ISSUE TITLE
Create new app logo

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/general-feedback#7]
**Describe the bug**
Need a new logo for app

**To Reproduce**
NA

**Expected behavior**
NA

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Brand: [e.g. Moto G2] NA
 - Version [e.g. Nougat] NA

**Additional context**
We need a new logo for the app, new logo should also be replaced with the current launcher icon and also needs to be updated in the assets directory

**Comment by andeladenaro** [comment]
Hi, my name is Andela Denaro, graphic design contributor. I read your issues and wanted to help you with the new logo. Here's my design for your apps.

![general feedback](https://user-images.githubusercontent.com/35057858/45946900-8521c400-c01c-11e8-886e-f46b000bae77.png)

I would appreciate hearing your opinion on this. Kind regards.

**Comment by arshadkazmi42** [comment]
Thanks @andeladenaro all of these looks awesome. Which one do you prefer? I like the purple color most. 
We also need a app redesign with similar theme. You can take a look at it here if you are interested #8

**Comment by andeladenaro** [comment]
Here's [Google Drive](https://drive.google.com/open?id=1EiozFm5LxYZyqIN7bAJUJOG8SoN9HRJ8)'s sharing file. Feel free to contact me if you need more file size.

**Comment by arshadkazmi42** [comment]
Thank you for the assets @andeladenaro .

Let me quickly generate launcher icons and create a new task for adding this to the app, it will be good first issue for starters.

**Comment by arshadkazmi42** [comment]
@andeladenaro Thanks for the logo. it has been added in readme file, I have also created a task to add this to launcher icons here #12 
Closing this issue now

**Comment by arshadkazmi42** [comment]
@andeladenaro also why don't you go ahead and add yourself to contributors list here #6

**Comment by andeladenaro** [comment]
Hey, you're welcome. My pleasure becoming your project contributor. I've add my self to contributor.md, thanks.

**Comment by arshadkazmi42** [comment]
@andeladenaro Cool, I have landed your PR 👍
